# Generated by Django 3.0.5 on 2021-04-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapIdsMST',
        ),
    ]
