# Generated by Django 3.0.5 on 2021-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsfEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('deadline_date', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('area_of_research', models.CharField(max_length=200)),
            ],
        ),
    ]
