# Generated by Django 3.0.5 on 2021-04-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='organizationName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
