# Generated by Django 3.0.5 on 2021-05-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_emailsubscription_organizationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='ID',
            field=models.IntegerField(unique=True),
        ),
    ]
