# Generated by Django 3.0.5 on 2021-04-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_bsfcall_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isfcalls',
            name='deadline',
        ),
        migrations.AddField(
            model_name='isfcalls',
            name='deadlineDate',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
