# Generated by Django 3.0.5 on 2021-01-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_bsfevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsfevents',
            name='event_id',
        ),
        migrations.AddField(
            model_name='bsfevents',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
