# Generated by Django 3.0.5 on 2021-06-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20210617_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='bsfCalls1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField(null=True, unique=True)),
                ('deadlineDate', models.DateField(blank=True, max_length=200, null=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('areaOfResearch', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EuCalls1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField(null=True, unique=True)),
                ('ccm2Id', models.IntegerField(default=1, unique=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('areaOfResearch', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('deadlineDate', models.DateField(blank=True, max_length=200, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnovationCalls1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField(null=True, unique=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('registrationDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('submissionDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('areaOfResearch', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('deadlineDate', models.DateField(blank=True, max_length=200, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsfCalls1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField(null=True, unique=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('registrationDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('submissionDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('institutionType', models.CharField(blank=True, max_length=200, null=True)),
                ('numberOfPartners', models.CharField(blank=True, max_length=200, null=True)),
                ('grantPeriod', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('deadlineDate', models.DateField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapIdsBSF1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapIdsEU1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapIdsINNOVATION1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapIdsISF1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapIdsMST1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapIdsTechnion1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MstCalls1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField(null=True, unique=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('submissionDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('deadlineDate', models.DateField(blank=True, max_length=200, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnionCalls1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField(null=True, unique=True)),
                ('deadlineDate', models.DateField(blank=True, max_length=200, null=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('areaOfResearch', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
