# Generated by Django 3.0.5 on 2021-05-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20210502_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscription',
            name='status',
        ),
    ]
