# Generated by Django 3.0.5 on 2021-01-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20210130_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsfevents',
            name='area_of_research',
        ),
        migrations.RemoveField(
            model_name='bsfevents',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bsfevents',
            name='organization_name',
        ),
    ]
