# Generated by Django 3.0.5 on 2021-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20210130_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsfevents',
            name='deadline_date',
        ),
        migrations.AddField(
            model_name='bsfevents',
            name='areaOfResearch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bsfevents',
            name='deadlineDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bsfevents',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bsfevents',
            name='organizationName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
