# Generated by Django 3.0.5 on 2021-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_remove_emailsubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
