# Generated by Django 3.0.5 on 2021-05-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_emailsubscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscription',
            name='status',
        ),
    ]
