# Generated by Django 3.0.5 on 2021-05-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_remove_emailsubscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapIdsTechnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnionCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField(null=True, unique=True)),
                ('deadlineDate', models.DateField(blank=True, max_length=200, null=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('areaOfResearch', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
