# Generated by Django 3.0.5 on 2021-02-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_auto_20210209_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsfEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlineDate', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('areaOfResearch', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BsfEvent',
        ),
    ]
