# Generated by Django 3.0.5 on 2021-03-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_auto_20210209_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsfCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('registrationDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('submissionDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('institutionType', models.CharField(blank=True, max_length=200, null=True)),
                ('numberOfPartners', models.CharField(blank=True, max_length=200, null=True)),
                ('grantPeriod', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='BsfEvents',
            new_name='BsfCalls',
        ),
    ]
