# Generated by Django 3.0.5 on 2021-03-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20210302_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('registrationDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('submissionDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='isfcalls',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
