# Generated by Django 3.0.5 on 2021-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_eucalls_mapidseu'),
    ]

    operations = [
        migrations.AddField(
            model_name='eucalls',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
