# Generated by Django 3.0.5 on 2021-03-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20210304_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationcalls',
            name='areaOfResearch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
