# Generated by Django 3.0.5 on 2021-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_eucalls_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eu_update', models.IntegerField()),
                ('technion_update', models.IntegerField()),
                ('bsf_update', models.IntegerField()),
                ('isf_update', models.IntegerField()),
                ('mst_update', models.IntegerField()),
                ('innovation_update', models.IntegerField()),
                ('ID', models.IntegerField(default=1, unique=True)),
            ],
        ),
    ]
