# Generated by Django 3.0.5 on 2021-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_innovationcalls_areaofresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(blank=True, max_length=200, null=True)),
                ('submissionDeadline', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
