# Generated by Django 3.0.5 on 2021-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='eucalls',
            name='ccm2Id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
