# Generated by Django 3.0.5 on 2021-03-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_mstcalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsfcalls',
            name='areaOfResearch2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
